### ISSUE TITLE
Fix delay issue when brewing potions.

### ISSUE THREAD

**Issue by xrtariq2594** [Terasology/Alchemy#2]
There's a noticeable delay between adding ingredients to the Herbalism Station (both the portable and non-portable versions), and when the recipes list on the right is updated. I presume either the update interval for the HerbalismWindow UI is too small, or there aren't any callbacks when herbs are placed on/removed from the HerbalismStation input slots.

**Comment by skaldarnar** [comment]
How many recipes are searched to find fitting ones? Could there also be a
bottleneck when looking through all recipes all over again? Probably this
needs some clever caching or better data structures for searching/comparing.

**Comment by xrtariq2594** [comment]
I believe this is related to the earlier issue in resolved in WorkstationCrafting.

Specifically, [this one](https://github.com/Terasology/WorkstationCrafting/commit/96e69447907dfb3e58820fb020baec32bdf93ecc).

**Comment by xrtariq2594** [comment]
Alright, I think I got this one fixed. The fix should be in the develop branch.

**Comment by xrtariq2594** [comment]
This issue has been resolved with the merge of PR #4.
