### ISSUE TITLE
Add comments and documentation to all classes

### ISSUE THREAD

**Issue by xrtariq2594** [Terasology/Alchemy#3]
Currently, many of the classes in this module are lacking documentation. So, the goal of this would be to add Javadoc comments to all of the classes.

**Comment by xrtariq2594** [comment]
I'm almost done with this one. I have only six more classes to add documentation to.

**Comment by xrtariq2594** [comment]
Alright, I added the rest of the documentation [in this commit](https://github.com/Terasology/Alchemy/commit/0e5bf78a479576efed236fa84c3f06a1fbef4c57).

**Comment by Cervator** [comment]
Closing as completed by #4
